-- Carta real de CORA, tomada de src/data/menu.json (la misma que se muestra
-- en la página pública). Los platos con variantes de tamaño (Personal /
-- Mediano / Familiar) se separan en filas independientes porque menu_items
-- solo admite un precio por fila.
insert into public.menu_items (nombre, descripcion, precio, categoria) values
  ('Ceviche de la Casa (Personal)', 'Filetes frescos de CABRILLA, pesca diaria, marinados en jugo de limón y mezclados con cebolla y cilantro.', 25, 'Para Compartir'),
  ('Ceviche de la Casa (Mediano)', 'Filetes frescos de CABRILLA, pesca diaria, marinados en jugo de limón y mezclados con cebolla y cilantro.', 40, 'Para Compartir'),
  ('Ceviche de la Casa (Familiar)', 'Filetes frescos de CABRILLA, pesca diaria, marinados en jugo de limón y mezclados con cebolla y cilantro.', 60, 'Para Compartir'),
  ('Ceviche Tropical (Mediano)', 'Pescado ESPADA seleccionado, marinado en jugo de limón y mezclado con cebolla y cilantro.', 40, 'Para Compartir'),
  ('Ceviche Tropical (Familiar)', 'Pescado ESPADA seleccionado, marinado en jugo de limón y mezclado con cebolla y cilantro.', 60, 'Para Compartir'),
  ('Ceviche Lobiteño (Mediano)', 'Una mezcla de filete de CABRILLA con PERCEBES exóticos, marinado en jugo de limón y mezclados con cebolla y cilantro.', 40, 'Para Compartir'),
  ('Ceviche Lobiteño (Familiar)', 'Una mezcla de filete de CABRILLA con PERCEBES exóticos, marinado en jugo de limón y mezclados con cebolla y cilantro.', 60, 'Para Compartir'),
  ('Ceviche de las Rocas (Mediano)', 'PERCEBES frescos y suaves, marinados en jugo de limón y mezclados con cebolla y cilantro.', 30, 'Para Compartir'),
  ('Ceviche de las Rocas (Familiar)', 'PERCEBES frescos y suaves, marinados en jugo de limón y mezclados con cebolla y cilantro.', 50, 'Para Compartir'),
  ('Ceviche del Océano (Mediano)', 'Filete de PESCADO fresco y una selección de MARISCOS, marinados en jugo de limón, especias, cebolla y cilantro.', 50, 'Para Compartir'),
  ('Ceviche del Océano (Familiar)', 'Filete de PESCADO fresco y una selección de MARISCOS, marinados en jugo de limón, especias, cebolla y cilantro.', 70, 'Para Compartir'),
  ('Cabrilla Frita (Mediano)', 'Un plato clásico del mar. Pescado fresco de la zona, frito a la perfección con una capa crujiente y dorada.', 40, 'Para Compartir'),
  ('Cabrilla Frita (Familiar)', 'Un plato clásico del mar. Pescado fresco de la zona, frito a la perfección con una capa crujiente y dorada.', 60, 'Para Compartir'),
  ('Sudado (Mediano)', 'Un plato sabroso del mar. Una especie de sopa con pescado fresco, cebolla, tomate, escabeche, acompañado con arroz.', 40, 'Para Compartir'),
  ('Sudado (Familiar)', 'Un plato sabroso del mar. Una especie de sopa con pescado fresco, cebolla, tomate, escabeche, acompañado con arroz.', 60, 'Para Compartir'),
  ('Chicharrón de Pescado o Pollo (Mediano)', 'Filetes aderezados con un toque de magia norteña y fritos a la perfección, crujiente por fuera y suave por dentro, acompañado de papas fritas.', 40, 'Para Compartir'),
  ('Chicharrón de Pescado o Pollo (Familiar)', 'Filetes aderezados con un toque de magia norteña y fritos a la perfección, crujiente por fuera y suave por dentro, acompañado de papas fritas.', 60, 'Para Compartir'),
  ('Arroz con Mariscos (Mediano)', 'Una mezcla de arroz cremoso con mariscos frescos y deliciosos. Una fusión de sabores y texturas del mar.', 40, 'Para Compartir'),
  ('Arroz con Mariscos (Familiar)', 'Una mezcla de arroz cremoso con mariscos frescos y deliciosos. Una fusión de sabores y texturas del mar.', 60, 'Para Compartir'),
  ('Majariscos Norteño (Mediano)', 'Una deliciosa combinación de plátano verde majado con mariscos seleccionados.', 40, 'Para Compartir'),
  ('Majariscos Norteño (Familiar)', 'Una deliciosa combinación de plátano verde majado con mariscos seleccionados.', 60, 'Para Compartir'),
  ('Cecina Amazónica (Mediano)', 'La cecina es un delicioso y tradicional alimento de la selva peruana. Tesoro culinario acompañada de patacones.', 40, 'Para Compartir'),
  ('Cecina Amazónica (Familiar)', 'La cecina es un delicioso y tradicional alimento de la selva peruana. Tesoro culinario acompañada de patacones.', 60, 'Para Compartir'),
  ('Seco de Chabelo (Mediano)', 'Deliciosa combinación de una salsa rica y aromática, plátano verde majado y su carne sabrosa.', 40, 'Para Compartir'),
  ('Seco de Chabelo (Familiar)', 'Deliciosa combinación de una salsa rica y aromática, plátano verde majado y su carne sabrosa.', 60, 'Para Compartir'),
  ('Salteado de Pescado', 'Trozos flameados con verduras, un toque de salsa de soya, servido con arroz blanco y papas fritas crujientes.', 30, 'Fondos Bien Taipa'),
  ('Salteado de Langostinos', 'Trozos flameados con verduras, un toque de salsa de soya, servido con arroz blanco y papas fritas crujientes.', 30, 'Fondos Bien Taipa'),
  ('Lomo Salteado', 'Trozos flameados con verduras, un toque de salsa de soya, servido con arroz blanco y papas fritas crujientes.', 30, 'Fondos Bien Taipa'),
  ('Salteado de Pollo', 'Trozos flameados con verduras, un toque de salsa de soya, servido con arroz blanco y papas fritas crujientes.', 28, 'Fondos Bien Taipa'),
  ('Salteado de Verduras', 'Trozos flameados con verduras, un toque de salsa de soya, servido con arroz blanco y papas fritas crujientes.', 28, 'Fondos Bien Taipa'),
  ('Filete de Pollo Frito', 'Filete suave y fresco, frito en poco aceite, acompañado de arroz blanco y papas fritas crujientes.', 18, 'Filetes Fritos'),
  ('Filete de Pescado', 'Filete suave y fresco, frito en poco aceite, acompañado de arroz blanco y papas fritas crujientes.', 18, 'Filetes Fritos'),
  ('Chuleta de Res/Cerdo', 'Filete suave y fresco, frito en poco aceite, acompañado de arroz blanco y papas fritas crujientes.', 18, 'Filetes Fritos'),
  ('Bisteck Frito', 'Filete suave y fresco, frito en poco aceite, acompañado de arroz blanco y papas fritas crujientes.', 25, 'Filetes Fritos'),
  ('Milanesa de Pescado', 'Filete apanado y frito, acompañado con arroz blanco, papas fritas y ensalada fresca.', 30, 'Milanesas'),
  ('Milanesa de Pollo', 'Filete apanado y frito, acompañado con arroz blanco, papas fritas y ensalada fresca.', 30, 'Milanesas'),
  ('Cora del Mar', 'Una exquisita combinación de chaufa con salteado de pescado, acompañado de papas fritas crujientes.', 40, 'Platos Especiales del Mar'),
  ('Tentáculos al Olivo', 'Láminas de pulpo cocinado en una salsa de aceitunas y aceite de oliva, con un toque de limón, acompañado con palta y pan baguette/galleta.', 50, 'Platos Especiales del Mar'),
  ('Pulpo Parrillero', 'Pulpo aderezado, a la parrilla, servido con camote glaseado y ensalada fresca.', 50, 'Platos Especiales del Mar'),
  ('Pescado Marinero', 'Filete de pescado frito bañado en una salsa especial de mariscos, servido con arroz blanco y papa dorada.', 35, 'En Salsas'),
  ('Ajos y Olas', 'Filete de pescado frito bañado en una rica salsa de ajo, servido con arroz blanco y papa dorada.', 28, 'En Salsas'),
  ('Pescado a lo Pobre', 'Filete frito en poco aceite, servido con arroz, huevo, chorizo, plátanos y papas fritas crujientes.', 30, 'A lo Pobre'),
  ('Bisteck a lo Pobre', 'Filete frito en poco aceite, servido con arroz, huevo, chorizo, plátanos y papas fritas crujientes.', 30, 'A lo Pobre'),
  ('Pollo a lo Pobre', 'Filete frito en poco aceite, servido con arroz, huevo, chorizo, plátanos y papas fritas crujientes.', 28, 'A lo Pobre'),
  ('Tortilla de Langostinos', 'Tortilla a base de huevo, acompañada con arroz blanco y papas fritas crujientes.', 28, 'Tortillas'),
  ('Tortilla de Percebes', 'Tortilla a base de huevo, acompañada con arroz blanco y papas fritas crujientes.', 28, 'Tortillas'),
  ('Chaufa de Pescado', 'Arroz salteado al wok con huevo, cebolla china, especias y su clásico saborcito oriental.', 18, 'Chaufa'),
  ('Chaufa de Pollo', 'Arroz salteado al wok con huevo, cebolla china, especias y su clásico saborcito oriental.', 28, 'Chaufa'),
  ('Chaufa de Langostinos', 'Arroz salteado al wok con huevo, cebolla china, especias y su clásico saborcito oriental.', 30, 'Chaufa'),
  ('Chaufa de Mariscos', 'Arroz salteado al wok con huevo, cebolla china, especias y su clásico saborcito oriental.', 18, 'Chaufa'),
  ('Chaufa de Bisteck', 'Arroz salteado al wok con huevo, cebolla china, especias y su clásico saborcito oriental.', 25, 'Chaufa'),
  ('Chaufa de Verduras', 'Arroz salteado al wok con huevo, cebolla china, especias y su clásico saborcito oriental.', 18, 'Chaufa'),
  ('Arroz Blanco', null, 4, 'Adicionales'),
  ('Plátanos Fritos', null, 8, 'Adicionales'),
  ('Papas Fritas', null, 8, 'Adicionales'),
  ('Ensalada Fresca', null, 8, 'Adicionales'),
  ('Camote Sancochado', null, 6, 'Adicionales'),
  ('Vaso de Chicha Morada', null, 15, 'Bebidas Naturales'),
  ('Chicha Morada 1L', null, 20, 'Bebidas Naturales'),
  ('Chicha Morada 1.5L', null, 5, 'Bebidas Naturales'),
  ('Agua Mineral 500ml', null, 3, 'Bebidas Naturales'),
  ('Agua Mineral 2L', null, 6, 'Bebidas Naturales'),
  ('Inka Cola, Coca-Cola, Fanta o Sprite (192ml)', null, 1.5, 'Gaseosas'),
  ('Inka Cola, Coca-Cola, Fanta o Sprite (296ml)', null, 2, 'Gaseosas'),
  ('Inka Cola, Coca-Cola, Fanta o Sprite (500ml)', null, 4, 'Gaseosas'),
  ('Inka Cola 625ml', null, 5, 'Gaseosas'),
  ('Inka Cola 1L', null, 7, 'Gaseosas'),
  ('Inka Cola, Coca-Cola, Fanta o Sprite (1.5L)', null, 10, 'Gaseosas'),
  ('Inka Cola 2.5L', null, 15, 'Gaseosas'),
  ('Guaraná 450ml', null, 3.5, 'Gaseosas'),
  ('Guaraná 2L', null, 10, 'Gaseosas'),
  ('Guaraná 3L', null, 15, 'Gaseosas'),
  ('Powerade 600ml', null, 4, 'Gaseosas'),
  ('Frugo 300ml', null, 4, 'Gaseosas'),
  ('Pilsen Cristal (lata) 355ml', null, 6, 'Cervezas'),
  ('Cusqueña (lata) 355ml', null, 7, 'Cervezas'),
  ('Pilsen Cristal (botella) 305ml', null, 6, 'Cervezas'),
  ('Cusqueña (botella) 310ml', null, 7, 'Cervezas'),
  ('Pilsen Cristal 630ml', null, 10, 'Cervezas'),
  ('Corona 330ml', null, 12, 'Cervezas'),
  ('Cusqueña 620ml', null, 8, 'Cervezas'),
  ('Mikes 550ml', null, 10, 'Cervezas')
;
